# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sso", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="scimsynclog",
            new_name="scim_sync_l_config__6055ab_idx",
            old_name="scim_sync_l_config__7d2f10_idx",
        ),
        migrations.RenameIndex(
            model_name="scimsynclog",
            new_name="scim_sync_l_externa_59c65e_idx",
            old_name="scim_sync_l_externa_3c8a9b_idx",
        ),
        migrations.RenameIndex(
            model_name="ssoconfig",
            new_name="sso_config_tenant__5632a9_idx",
            old_name="sso_config_tenant__a8f3c2_idx",
        ),
        migrations.RenameIndex(
            model_name="ssoconfig",
            new_name="sso_config_project_e80424_idx",
            old_name="sso_config_project_91b4e1_idx",
        ),
        migrations.AlterField(
            model_name="ssoconfig",
            name="attribute_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map IdP attribute URIs to local fields, e.g. {'email': '...', 'first_name': '...'}",
            ),
        ),
    ]
