# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_payload_format"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="webhook",
            name="webhooks_webhook_team_idx",
        ),
    ]
