# Generated by Django 5.2.14 on 2026-05-26 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("monitoring", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmaintenance",
            name="monitors",
            field=models.ManyToManyField(
                blank=True,
                related_name="scheduled_maintenances",
                to="monitoring.monitor",
            ),
        ),
        migrations.AddField(
            model_name="scheduledmaintenance",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_maintenances",
                to="tenancy.project",
            ),
        ),
        migrations.AddField(
            model_name="scheduledmaintenance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_maintenances",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmaintenance",
            index=models.Index(
                fields=["tenant", "project"], name="maintenance_tenant__ca605a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledmaintenance",
            index=models.Index(
                fields=["status", "starts_at"], name="maintenance_status_eae1de_idx"
            ),
        ),
    ]
