# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_recurrence"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scheduledmaintenance",
            name="maintenance_scheduledmaintenance_team_idx",
        ),
        migrations.AlterField(
            model_name="scheduledmaintenance",
            name="recurrence_interval",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Repeat every N days/weeks/months."
            ),
        ),
        migrations.AlterField(
            model_name="scheduledmaintenance",
            name="recurrence_weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="For weekly recurrence: ISO weekdays 0=Monday … 6=Sunday.",
            ),
        ),
    ]
