# Generated by Django 5.2.14 on 2026-05-26 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("api", "API / HTTP"),
                            ("website", "Website"),
                            ("ping", "Ping (ICMP)"),
                            ("tcp", "TCP Port"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        default="api",
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=2048)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("interval_seconds", models.PositiveIntegerField(default=60)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("retries", models.PositiveSmallIntegerField(default=3)),
                ("probe_locations", models.JSONField(default=list)),
                ("criteria", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                ("body", models.TextField(blank=True)),
                ("alert_on_failure", models.BooleanField(default=True)),
                ("is_paused", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("degraded", "Degraded"),
                            ("offline", "Offline"),
                            ("disabled", "Disabled"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("next_check_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_monitors",
                        to="incidents.incident",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_monitor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonitorGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monitors",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="monitoring.monitor"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_groups",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_groups",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_monitor_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Probe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                (
                    "probe_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probes",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="probes",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_probe",
                "ordering": ["location"],
            },
        ),
        migrations.CreateModel(
            name="MonitorCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checked_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("timeout", "Timeout"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="monitoring.monitor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_checks",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "triggered_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggering_checks",
                        to="incidents.incident",
                    ),
                ),
                (
                    "probe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checks",
                        to="monitoring.probe",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_monitor_check",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["tenant", "project"], name="monitoring__tenant__d92acc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(fields=["status"], name="monitoring__status_ba861c_idx"),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["next_check_at"], name="monitoring__next_ch_735cb6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["tenant", "is_paused", "next_check_at"],
                name="monitoring__tenant__b2b18d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitorgroup",
            index=models.Index(
                fields=["tenant", "project"], name="monitoring__tenant__32eb01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="probe",
            index=models.Index(
                fields=["tenant", "project"], name="monitoring__tenant__074c7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitorcheck",
            index=models.Index(
                fields=["monitor", "-checked_at"], name="monitoring__monitor_ec885d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitorcheck",
            index=models.Index(
                fields=["tenant", "-checked_at"], name="monitoring__tenant__a3dd69_idx"
            ),
        ),
    ]
