# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_monitor_extensions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="monitor",
            name="monitoring_monitor_team_idx",
        ),
        migrations.RemoveIndex(
            model_name="monitorgroup",
            name="monitoring_monitorgroup_team_idx",
        ),
    ]
