# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0002_resource_policy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resourcepolicy",
            new_name="rbac_resour_project_0a91d4_idx",
            old_name="rbac_rp_project_rtype_idx",
        ),
        migrations.RenameIndex(
            model_name="resourcepolicy",
            new_name="rbac_resour_role_id_e1ae88_idx",
            old_name="rbac_rp_role_rtype_rid_idx",
        ),
    ]
