# Generated by Django 5.2.14 on 2026-05-26 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("actor_id", models.UUIDField()),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("api_key", "API Key"),
                            ("system", "System"),
                            ("scim", "SCIM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("prev_hash", models.CharField(max_length=64)),
                ("record_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="audit_log_tenant__dfd678_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_log_resourc_2570dd_idx",
                    ),
                    models.Index(
                        fields=["tenant", "action"], name="audit_log_tenant__ed9ce1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("monitor_checks", "Monitor Checks"),
                            ("audit_logs", "Audit Logs"),
                            ("webhook_deliveries", "Webhook Deliveries"),
                            ("incidents_resolved", "Resolved Incidents"),
                        ],
                        max_length=30,
                    ),
                ),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("archive_to_s3", models.BooleanField(default=False)),
                ("s3_bucket", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_policies",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_policies",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_retention_policy",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "data_type"),
                        name="unique_retention_per_project_datatype",
                    )
                ],
            },
        ),
    ]
