# Generated by Django 5.2.14 on 2026-05-26 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "custom_domain",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("primary_color", models.CharField(default="#0066cc", max_length=7)),
                ("custom_css", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_pages",
                        to="tenancy.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_pages",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "status_pages_page",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StatusPageAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="status_pages.statuspage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_page_announcements",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "status_pages_announcement",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusPageResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_page_resources",
                        to="monitoring.monitor",
                    ),
                ),
                (
                    "monitor_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_page_resources",
                        to="monitoring.monitorgroup",
                    ),
                ),
                (
                    "status_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="status_pages.statuspage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_page_resources",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "status_pages_resource",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StatusPageSubscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_token", models.CharField(blank=True, max_length=64)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="status_pages.statuspage",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_page_subscribers",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "status_pages_subscriber",
            },
        ),
        migrations.AddIndex(
            model_name="statuspage",
            index=models.Index(
                fields=["tenant", "project"], name="status_page_tenant__40f8ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statuspage",
            constraint=models.UniqueConstraint(
                fields=("tenant", "slug"), name="unique_status_page_slug_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="statuspageannouncement",
            index=models.Index(
                fields=["status_page", "is_active"],
                name="status_page_status__3b4457_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statuspageresource",
            index=models.Index(
                fields=["status_page", "order"], name="status_page_status__7e1b8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="statuspagesubscriber",
            constraint=models.UniqueConstraint(
                fields=("status_page", "email"), name="unique_subscriber_per_page"
            ),
        ),
    ]
