# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status_pages", "0004_subscriber_phone_verification_token"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="statuspage",
            name="status_pages_statuspage_team_idx",
        ),
    ]
