# Generated by Django 5.2.14 on 2026-05-26 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("monitoring", "0001_initial"),
        ("tenancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="monitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="monitoring.monitor",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="tenancy.project",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incidentnote",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incidentnote",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentnote",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_notes",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="incident",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postmortem",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentpostmortem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postmortems",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incidentseverity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_severities",
                to="tenancy.project",
            ),
        ),
        migrations.AddField(
            model_name="incidentseverity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_severities",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="severity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidents",
                to="incidents.incidentseverity",
            ),
        ),
        migrations.AddField(
            model_name="incidentstate",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_states",
                to="tenancy.project",
            ),
        ),
        migrations.AddField(
            model_name="incidentstate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_states",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidents",
                to="incidents.incidentstate",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentnote",
            index=models.Index(
                fields=["incident", "created_at"], name="incidents_n_inciden_a1ab1f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentseverity",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_incident_severity_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentstate",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_incident_state_per_project"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["tenant", "project"], name="incidents_i_tenant__10c39a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["tenant", "-triggered_at"],
                name="incidents_i_tenant__1a3a7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["monitor"], name="incidents_i_monitor_436210_idx"
            ),
        ),
    ]
