# Generated by Django 5.2.14 on 2026-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0004_escalation_workflows"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_incident_team_idx",
        ),
        migrations.RenameIndex(
            model_name="escalationpolicy",
            new_name="incidents_e_tenant__c8c09e_idx",
            old_name="incidents_es_tenant__a0f0f0_idx",
        ),
        migrations.RenameIndex(
            model_name="incidentworkflowrule",
            new_name="incidents_w_tenant__dcd974_idx",
            old_name="incidents_wf_tenant__b1b1b1_idx",
        ),
        migrations.AlterField(
            model_name="escalationpolicy",
            name="severity_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Empty = all severities; otherwise list of severity names.",
            ),
        ),
        migrations.AlterField(
            model_name="escalationstep",
            name="delay_minutes",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Minutes after incident trigger (step 1) or previous step.",
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflowrule",
            name="actions",
            field=models.JSONField(
                default=list,
                help_text='List of {"type": "webhook"|"assign"|"notify_user", ...}',
            ),
        ),
        migrations.AlterField(
            model_name="incidentworkflowrule",
            name="conditions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='e.g. {"severity_names": ["critical"], "delay_minutes": 15}',
            ),
        ),
    ]
